site_name: My Feature Documentation # FIXME

plugins:
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
  - i18n:
      default_language: en     # Default to English
      languages:
        default:               # The default language
          name: Default (en)
          build: true
        en:                    # English
          name: English
          build: true
        # vi:                  # SAMPLE: additional language, Vietnamese
          # name: Tiếng Việt
          # build: true
      # nav_translations:      # SAMPLE: translation of the navigation (edit as appropriate)
        # vi:
          # Home: Trang chủ
          # User Guide: Hướng dẫn sử dụng
          # Package Loading & Options: Cách tải gói và các tuỳ chọn
          # Typesetting Event-B Models: Đánh chữ cho mẫu Event-B
  
  - with-pdf                   # Generate PDF versions (for all languages)
  - search                     # Enable search


site_description: Documentation of some useful     # FIXME
site_author: Firstname Lastname                    # FIXME

# FIXME The link to the repository URL on GitHub. At the moment, it points to the CamilleX
repo_url: https://eventB-soton.github.io/XEventB
# FIXME The name of the reposotory corresponding the above URL
repo_name: My Repository
theme: material                # Use the standard material theme https://squidfunk.github.io/mkdocs-material/

# Navigation: This need to be reflected for all languages.
# For example, this expect to have index.en.md for English and index.vi.md for Vietnamese.
# Similarly for the whole navigation structure
nav:
- Home: index.md               # The home page is index.md
# SAMPLE: Additional navigation
# - User Guide:
  # - Package Loading & Options: user_guide/package_loading_and_options.md
  # - Typesetting Event-B Models: user_guide/typesetting_Event-B_models.md

extra:                         # Extra: using mike for maintaining different version
  version:
    provider: mike